language: swift
cache:
 - cocoapods
before_install:
   - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet
   - pod install --repo-update
os: osx
osx_image: xcode10.1

script:
 - xcodebuild build-for-testing -workspace CondorUIComponents.xcworkspace -scheme CondorUIComponents -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
 - xctool run-tests -workspace CondorUIComponents.xcworkspace -scheme CondorUIComponents -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO

notifications:
 slack: cebroker:bpRviKaWRDVUEHU7yPJk2ucw